  MatrixHelperRewrite[m
  bullet-drop[m
  cv_testbench[m
  develop[m
  enhancement/GenericOnExecute[m
  enhancement/refactor-rel-drive[m
  feature/bullet-drop[m
* [32mfeature/custom-gui[m
  feature/hud_display[m
  feature/nxp-fusion-algorithm[m
  feature/swerve[m
  general_testbench[m
  main[m
  refactoredChainsaw[m
  robot/dart[m
  robots/engineer[m
  robots/engineer-deprecated[m
  robots/hero[m
  robots/sentry[m
  subsystems/feeder[m
  [31mremotes/origin/HEAD[m -> origin/main
  [31mremotes/origin/MatrixHelperRewrite[m
  [31mremotes/origin/bug/hopper-start-delay[m
  [31mremotes/origin/cv_testbench[m
  [31mremotes/origin/devBoardUpgrade[m
  [31mremotes/origin/develop[m
  [31mremotes/origin/documentation/re-comment-code-base[m
  [31mremotes/origin/enhancement/refactor-rel-drive[m
  [31mremotes/origin/feature/auto-setup[m
  [31mremotes/origin/feature/bullet-drop[m
  [31mremotes/origin/feature/custom-gui[m
  [31mremotes/origin/feature/find-absolute-position[m
  [31mremotes/origin/feature/graber[m
  [31mremotes/origin/feature/hud_display[m
  [31mremotes/origin/feature/limit-switch-2.0[m
  [31mremotes/origin/feature/nxp-fusion-algorithm[m
  [31mremotes/origin/feature/ref-protocal[m
  [31mremotes/origin/feature/ref-system-coms[m
  [31mremotes/origin/feature/ref-system-integration[m
  [31mremotes/origin/feature/robot-state[m
  [31mremotes/origin/feature/sentry-patrol[m
  [31mremotes/origin/feature/servo_standard[m
  [31mremotes/origin/feature/solenoid[m
  [31mremotes/origin/feature/swerve[m
  [31mremotes/origin/feature/ultrasonic-integration[m
  [31mremotes/origin/features/cv-embedded-comms[m
  [31mremotes/origin/features/limit-switch[m
  [31mremotes/origin/general_testbench[m
  [31mremotes/origin/main[m
  [31mremotes/origin/members/jeff[m
  [31mremotes/origin/merges/merging-subsystem-code[m
  [31mremotes/origin/origin/testbench-typeC[m
  [31mremotes/origin/project-changes/rename-project-folder[m
  [31mremotes/origin/refactoredChainsaw[m
  [31mremotes/origin/robot/dart[m
  [31mremotes/origin/robots/aerial[m
  [31mremotes/origin/robots/engineer[m
  [31mremotes/origin/robots/engineer-deprecated[m
  [31mremotes/origin/robots/hero[m
  [31mremotes/origin/robots/keyboard_control[m
  [31mremotes/origin/robots/sentry[m
  [31mremotes/origin/robots/standard[m
  [31mremotes/origin/shooter-PIDConstants[m
  [31mremotes/origin/subsystems/chassis[m
  [31mremotes/origin/subsystems/feeder[m
  [31mremotes/origin/subsystems/flywheel[m
  [31mremotes/origin/subsystems/gimbal[m
  [31mremotes/origin/testbench-typeC[m
